# Generated by Django 3.2.4 on 2021-06-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JAGUARETEAPP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
