# Generated by Django 3.2.4 on 2021-06-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAGUARETEAPP', '0002_delete_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=None, upload_to='imagenes/'),
        ),
    ]
