# Generated by Django 3.2.4 on 2021-06-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JAGUARETEAPP', '0004_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='color',
        ),
    ]
