# Generated by Django 3.2.4 on 2021-06-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAGUARETEAPP', '0005_rename_nombre_producto_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='product',
        ),
        migrations.AddField(
            model_name='pedido',
            name='product',
            field=models.ManyToManyField(to='JAGUARETEAPP.Producto'),
        ),
    ]
