# Generated by Django 3.2.4 on 2021-07-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JAGUARETEAPP', '0007_auto_20210704_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
