# Generated by Django 3.2.4 on 2021-07-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAGUARETEAPP', '0009_auto_20210704_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='marca',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='categ',
        ),
        migrations.AddField(
            model_name='categoria',
            name='marca',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
