# Generated by Django 3.2.4 on 2021-07-05 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JAGUARETEAPP', '0010_auto_20210704_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='moderador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='marca',
            field=models.CharField(max_length=30),
        ),
    ]
